'use client';
import * as Dialog from '@radix-ui/react-dialog';
import { AlertTriangle,Banknote,Building2,CheckCircle2,CircleDollarSign,CreditCard,Download,Eye,FileCheck2,Landmark,Plus,ReceiptText,Search,Wifi,X } from 'lucide-react';
import { useEffect,useMemo,useState } from 'react';
import { createId } from '@/lib/id';
import { Badge,Button } from './ui';

type InvoiceStatus='DRAFT'|'ISSUED'|'PARTIALLY_PAID'|'PAID'|'OVERDUE'|'CANCELLED';
type Payment={id:string;date:string;amount:number;method:string;reference:string;receivedBy:string;details?:Record<string,string>};
type Invoice={id:string;number:string;resident:string;residentId:string;branch:string;category:string;issueDate:string;dueDate:string;amount:number;paid:number;status:InvoiceStatus;description:string;payments:Payment[]};
const today=()=>new Date().toISOString().slice(0,10);
const seed:Invoice[]=[
 {id:'1',number:'INV-2026-0018',resident:'Eleanor Bennett',residentId:'RES-001',branch:'Willow Grove Residence',category:'Monthly care',issueDate:'2026-07-01',dueDate:'2026-07-15',amount:185000,paid:185000,status:'PAID',description:'Residential care package — July 2026',payments:[{id:'p1',date:'2026-07-10',amount:185000,method:'Bank transfer',reference:'TRX-88421',receivedBy:'Accounts'}]},
 {id:'2',number:'INV-2026-0019',resident:'Arthur Reed',residentId:'RES-002',branch:'Willow Grove Residence',category:'Monthly care',issueDate:'2026-07-01',dueDate:'2026-07-15',amount:210000,paid:100000,status:'PARTIALLY_PAID',description:'Enhanced residential care package — July 2026',payments:[{id:'p2',date:'2026-07-12',amount:100000,method:'Card',reference:'CARD-9211',receivedBy:'Accounts'}]},
 {id:'3',number:'INV-2026-0020',resident:'Mabel Foster',residentId:'RES-003',branch:'Willow Grove Residence',category:'Clinical services',issueDate:'2026-07-05',dueDate:'2026-07-20',amount:42500,paid:0,status:'OVERDUE',description:'Doctor consultation and laboratory services',payments:[]},
];
const blank={resident:'',residentId:'',branch:'Willow Grove Residence',category:'Monthly care',issueDate:'',dueDate:'',amount:0,description:'',status:'ISSUED' as InvoiceStatus};
const money=(value:number)=>new Intl.NumberFormat('en-LK',{style:'currency',currency:'LKR',maximumFractionDigits:0}).format(value);

export function BillingPage(){
 const[mounted,setMounted]=useState(false),[invoices,setInvoices]=useState<Invoice[]>([]),[search,setSearch]=useState(''),[filter,setFilter]=useState('ALL'),[open,setOpen]=useState(false),[selected,setSelected]=useState<Invoice|null>(null),[paying,setPaying]=useState<Invoice|null>(null);
 useEffect(()=>{const saved=localStorage.getItem('carenest_billing');setInvoices(saved?JSON.parse(saved):seed);setMounted(true)},[]);
 const persist=(next:Invoice[])=>{setInvoices(next);localStorage.setItem('carenest_billing',JSON.stringify(next))};
 const visible=useMemo(()=>invoices.filter(invoice=>`${invoice.number} ${invoice.resident} ${invoice.residentId} ${invoice.branch} ${invoice.category}`.toLowerCase().includes(search.toLowerCase())&&(filter==='ALL'||invoice.status===filter)),[invoices,search,filter]);
 const outstanding=invoices.reduce((sum,item)=>sum+Math.max(0,item.amount-item.paid),0),collected=invoices.reduce((sum,item)=>sum+item.paid,0);
 const exportCsv=()=>{const headers=['Invoice','Resident','Resident ID','Branch','Category','Issue date','Due date','Amount','Paid','Balance','Status'];const rows=visible.map(item=>[item.number,item.resident,item.residentId,item.branch,item.category,item.issueDate,item.dueDate,item.amount,item.paid,item.amount-item.paid,item.status]);const quote=(v:unknown)=>`"${String(v).replaceAll('"','""')}"`;const blob=new Blob(['\uFEFF',[headers,...rows].map(row=>row.map(quote).join(',')).join('\r\n')],{type:'text/csv'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`carenest-billing-${today()}.csv`;link.click();URL.revokeObjectURL(link.href)};
 if(!mounted)return <main className="min-h-screen bg-cream lg:ml-64"><div className="p-9"><div className="h-[650px] animate-pulse rounded-2xl bg-white"/></div></main>;
 return <main className="min-h-screen lg:ml-64"><header className="border-b bg-white px-5 py-5 md:px-9"><div className="mx-auto flex max-w-[1500px] flex-wrap items-center justify-between gap-4"><div><p className="eyebrow">Finance & accounts</p><h1 className="mt-1 text-2xl font-bold">Billing</h1><p className="mt-1 text-sm text-sage">Manage resident invoices, balances and payment records.</p></div><div className="flex gap-2"><button onClick={exportCsv} className="flex h-10 items-center gap-2 rounded-xl border bg-white px-4 text-sm font-semibold"><Download size={16}/>Export</button><Button onClick={()=>setOpen(true)}><Plus size={17}/>Create invoice</Button></div></div></header>
 <div className="mx-auto max-w-[1500px] p-5 md:p-9"><section className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Summary icon={CircleDollarSign} label="Total billed" value={money(invoices.reduce((sum,item)=>sum+item.amount,0))}/><Summary icon={CheckCircle2} label="Payments received" value={money(collected)}/><Summary icon={AlertTriangle} label="Outstanding balance" value={money(outstanding)}/><Summary icon={ReceiptText} label="Overdue invoices" value={invoices.filter(item=>item.status==='OVERDUE').length.toString()}/></section>
 <section className="card overflow-hidden"><div className="flex flex-col gap-3 border-b p-5 md:flex-row md:items-center md:justify-between"><div><p className="eyebrow">Accounts receivable</p><h2 className="mt-1 text-lg font-bold">Resident invoices</h2></div><div className="flex gap-2"><label className="relative"><Search size={17} className="absolute left-3 top-3 text-sage"/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search invoice or resident..." className="h-11 w-64 rounded-xl border pl-10 pr-3 text-sm"/></label><select value={filter} onChange={event=>setFilter(event.target.value)} className="h-11 rounded-xl border bg-white px-3 text-sm font-semibold"><option value="ALL">All statuses</option>{['DRAFT','ISSUED','PARTIALLY_PAID','PAID','OVERDUE','CANCELLED'].map(value=><option key={value}>{value}</option>)}</select></div></div>
 <div className="overflow-x-auto"><table className="w-full text-left"><thead><tr className="bg-cream/60 text-[11px] uppercase tracking-wider text-sage"><th className="px-5 py-3">Invoice</th><th className="px-4 py-3">Resident</th><th className="px-4 py-3">Dates</th><th className="px-4 py-3">Amount</th><th className="px-4 py-3">Balance</th><th className="px-4 py-3">Status</th><th className="px-4 py-3"></th></tr></thead><tbody>{visible.map(invoice=><tr key={invoice.id} className="border-t hover:bg-mint/20"><td className="px-5 py-4"><p className="font-semibold">{invoice.number}</p><p className="text-xs text-sage">{invoice.category}</p></td><td className="px-4"><p className="text-sm font-semibold">{invoice.resident}</p><p className="text-xs text-sage">{invoice.branch}</p></td><td className="whitespace-nowrap px-4 text-sm"><p>Issued {invoice.issueDate}</p><p className="text-xs text-sage">Due {invoice.dueDate}</p></td><td className="px-4 text-sm font-semibold">{money(invoice.amount)}</td><td className="px-4"><p className="text-sm font-bold">{money(invoice.amount-invoice.paid)}</p><p className="text-xs text-sage">{money(invoice.paid)} paid</p></td><td className="px-4"><InvoiceBadge status={invoice.status}/></td><td className="px-4"><div className="flex gap-1"><button onClick={()=>setSelected(invoice)} aria-label="View invoice" className="grid h-9 w-9 place-items-center rounded-xl border"><Eye size={16}/></button>{invoice.amount>invoice.paid&&invoice.status!=='CANCELLED'&&<button onClick={()=>setPaying(invoice)} className="flex h-9 items-center gap-1 rounded-xl bg-forest px-3 text-xs font-semibold text-white"><CreditCard size={14}/>Payment</button>}</div></td></tr>)}</tbody></table></div>{!visible.length&&<div className="grid min-h-64 place-items-center text-center"><div><ReceiptText className="mx-auto text-sage"/><h3 className="mt-3 font-bold">No invoices found</h3><p className="text-sm text-sage">Change the filters or create a new invoice.</p></div></div>}</section></div>
 <InvoiceDialog open={open} close={()=>setOpen(false)} save={data=>{const sequence=Math.max(0,...invoices.map(item=>Number(item.number.split('-').pop())||0))+1;persist([{...data,id:createId('invoice'),number:`INV-${new Date().getFullYear()}-${String(sequence).padStart(4,'0')}`,paid:0,payments:[]},...invoices]);setOpen(false)}}/>{selected&&<InvoiceDetails invoice={selected} close={()=>setSelected(null)}/>} {paying&&<PaymentDialog invoice={paying} close={()=>setPaying(null)} save={payment=>{persist(invoices.map(item=>{if(item.id!==paying.id)return item;const paid=Math.min(item.amount,item.paid+payment.amount);return {...item,paid,payments:[...item.payments,payment],status:paid>=item.amount?'PAID':'PARTIALLY_PAID'}}));setPaying(null)}}/>}</main>
}
function InvoiceDialog({open,close,save}:{open:boolean;close:()=>void;save:(data:Omit<Invoice,'id'|'number'|'paid'|'payments'>)=>void}){const[form,setForm]=useState(blank);useEffect(()=>{if(open){const issue=today(),due=new Date();due.setDate(due.getDate()+14);setForm({...blank,issueDate:issue,dueDate:due.toISOString().slice(0,10)})}},[open]);const field=(key:keyof typeof blank,value:string|number)=>setForm({...form,[key]:value});return <Dialog.Root open={open} onOpenChange={value=>!value&&close()}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-40 bg-black/55"/><Dialog.Content className="fixed left-1/2 top-1/2 z-50 w-[calc(100%-2rem)] max-w-2xl -translate-x-1/2 -translate-y-1/2 rounded-2xl bg-white p-6"><Dialog.Title className="text-xl font-bold">Create invoice</Dialog.Title><Dialog.Description className="mt-1 text-sm text-sage">Record resident charges and payment due date.</Dialog.Description><button onClick={close} className="absolute right-5 top-5"><X/></button><div className="mt-6 grid gap-4 sm:grid-cols-2"><Input label="Resident name" value={form.resident} set={value=>field('resident',value)}/><Input label="Resident ID" value={form.residentId} set={value=>field('residentId',value)}/><Input label="Branch" value={form.branch} set={value=>field('branch',value)}/><Select label="Category" value={form.category} set={value=>field('category',value)} values={['Monthly care','Clinical services','Medication','Therapy','Accommodation','Additional services']}/><Input label="Issue date" type="date" value={form.issueDate} set={value=>field('issueDate',value)}/><Input label="Due date" type="date" value={form.dueDate} set={value=>field('dueDate',value)}/><Input label="Amount (LKR)" type="number" value={String(form.amount)} set={value=>field('amount',Number(value))}/><Select label="Initial status" value={form.status} set={value=>field('status',value)} values={['DRAFT','ISSUED']}/><label className="text-sm font-semibold sm:col-span-2">Description<textarea rows={3} value={form.description} onChange={event=>field('description',event.target.value)} className="mt-1.5 w-full rounded-xl border p-3 font-normal"/></label></div><div className="mt-6 flex justify-end gap-2"><button onClick={close} className="h-10 rounded-xl border px-4">Cancel</button><Button disabled={!form.resident||!form.residentId||form.amount<=0} onClick={()=>save(form)}>Create invoice</Button></div></Dialog.Content></Dialog.Portal></Dialog.Root>}
function PaymentDialog({invoice,close,save}:{invoice:Invoice;close:()=>void;save:(payment:Payment)=>void}){
 const[amount,setAmount]=useState(invoice.amount-invoice.paid),[method,setMethod]=useState('Bank transfer'),[reference,setReference]=useState(''),[fields,setFields]=useState<Record<string,string>>({invoiceNumber:invoice.number,paymentDate:today()}),[cardFlipped,setCardFlipped]=useState(false),[receiptError,setReceiptError]=useState('');
 const set=(key:string,value:string)=>setFields(current=>({...current,[key]:value}));
 const required=method==='Card'?['cardholderName','cardNumber','expiryDate','cvv']:method==='Cheque'?['chequeNumber','chequeBank','chequeDate','accountName']:method==='Bank transfer'?['transactionId','transferBank','transferDate','accountName','receiptDataUrl']:method==='Cash'?['invoiceNumber','receivedBy']:['onlineProvider','transactionId','transferDate','payer','receiptDataUrl'];
 const valid=amount>0&&amount<=invoice.amount-invoice.paid&&required.every(key=>fields[key]?.trim());
 const submit=()=>{if(!valid)return;const details=method==='Card'?{cardLast4:fields.cardNumber.replace(/\s/g,'').slice(-4),expiryDate:fields.expiryDate,cardholderName:fields.cardholderName||''}:Object.fromEntries(Object.entries(fields).filter(([key])=>!['cardNumber','cvv'].includes(key)));save({id:createId('payment'),date:today(),amount,method,reference:reference||fields.transactionId||fields.chequeNumber||fields.invoiceNumber||'',receivedBy:fields.receivedBy||'Current user',details})};
 return <Dialog.Root open onOpenChange={value=>!value&&close()}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-40 bg-black/55"/><Dialog.Content className="fixed left-1/2 top-1/2 z-50 max-h-[90vh] w-[calc(100%-2rem)] max-w-xl -translate-x-1/2 -translate-y-1/2 overflow-y-auto rounded-2xl bg-white p-6"><Dialog.Title className="text-xl font-bold">Record payment</Dialog.Title><Dialog.Description className="mt-1 text-sm text-sage">{invoice.number} · Balance {money(invoice.amount-invoice.paid)}</Dialog.Description><button onClick={close} className="absolute right-5 top-5"><X/></button><div className="mt-6 grid gap-4 sm:grid-cols-2"><Input label="Payment amount (LKR)" type="number" value={String(amount)} set={value=>setAmount(Number(value))}/><Select label="Payment method" value={method} set={value=>{setMethod(value);setReference('');setFields(current=>({...current,receiptDataUrl:'',receiptName:'',receiptType:''}));setReceiptError('')}} values={['Bank transfer','Card','Cash','Cheque','Online transfer']}/>
 {method!=='Card'&&<div className="sm:col-span-2"><PaymentMethodPreview method={method} amount={amount} invoice={invoice.number} fields={fields}/></div>}
 {method==='Card'&&<><div className="sm:col-span-2"><CardPreview holder={fields.cardholderName} number={fields.cardNumber} expiry={fields.expiryDate} cvv={fields.cvv} flipped={cardFlipped}/></div><Input label="Cardholder name" value={fields.cardholderName||''} set={value=>set('cardholderName',value.toUpperCase())}/><Input label="Card number" value={fields.cardNumber||''} set={value=>{const digits=value.replace(/\D/g,'').slice(0,16);set('cardNumber',digits.replace(/(\d{4})(?=\d)/g,'$1 '))}}/><Input label="Expiry date (MM/YY)" value={fields.expiryDate||''} set={value=>{const digits=value.replace(/\D/g,'').slice(0,4);set('expiryDate',digits.length>2?`${digits.slice(0,2)}/${digits.slice(2)}`:digits)}}/><Input label="CVV code" type="password" value={fields.cvv||''} set={value=>set('cvv',value.replace(/\D/g,'').slice(0,4))} onFocus={()=>setCardFlipped(true)} onBlur={()=>setCardFlipped(false)}/><p className="rounded-xl bg-[#fff3dc] p-3 text-xs text-[#946c1f] sm:col-span-2">For payment security, CareNest saves only the last four card digits and expiry date. The complete card number and CVV are never stored.</p></>}
 {method==='Cheque'&&<><Input label="Cheque number" value={fields.chequeNumber||''} set={value=>set('chequeNumber',value)}/><Input label="Bank name" value={fields.chequeBank||''} set={value=>set('chequeBank',value)}/><Input label="Cheque date" type="date" value={fields.chequeDate||''} set={value=>set('chequeDate',value)}/><Input label="Account holder name" value={fields.accountName||''} set={value=>set('accountName',value)}/><Input label="Branch / clearing details" value={fields.chequeBranch||''} set={value=>set('chequeBranch',value)}/></>}
 {method==='Bank transfer'&&<><Input label="Transaction / transfer ID" value={fields.transactionId||''} set={value=>set('transactionId',value)}/><Input label="Bank name" value={fields.transferBank||''} set={value=>set('transferBank',value)}/><Input label="Transfer date" type="date" value={fields.transferDate||''} set={value=>set('transferDate',value)}/><Input label="Sender account name" value={fields.accountName||''} set={value=>set('accountName',value)}/><Input label="Sender account last 4 digits" value={fields.accountLast4||''} set={value=>set('accountLast4',value.replace(/\D/g,'').slice(0,4))}/></>}
 {method==='Cash'&&<><Input label="Invoice number" value={fields.invoiceNumber||invoice.number} set={value=>set('invoiceNumber',value)}/><Input label="Received by" value={fields.receivedBy||''} set={value=>set('receivedBy',value)}/><Input label="Receipt number" value={fields.receiptNumber||''} set={value=>set('receiptNumber',value)}/><Input label="Payment date" type="date" value={fields.paymentDate||today()} set={value=>set('paymentDate',value)}/></>}
 {method==='Online transfer'&&<><Select label="Payment provider" value={fields.onlineProvider||''} set={value=>set('onlineProvider',value)} values={['','PayHere','Stripe','PayPal','Bank portal','Other']}/><Input label="Transaction ID" value={fields.transactionId||''} set={value=>set('transactionId',value)}/><Input label="Transfer date" type="date" value={fields.transferDate||''} set={value=>set('transferDate',value)}/><Input label="Payer email or mobile" value={fields.payer||''} set={value=>set('payer',value)}/></>}
 {(method==='Online transfer'||method==='Bank transfer')&&<label className="text-sm font-semibold sm:col-span-2">Upload {method.toLowerCase()} receipt<input type="file" accept="image/png,image/jpeg,image/webp,application/pdf" onChange={event=>{const file=event.target.files?.[0];setReceiptError('');if(!file)return;if(file.size>2*1024*1024){setReceiptError('Receipt must be 2 MB or smaller.');event.target.value='';return}const reader=new FileReader();reader.onload=()=>setFields(current=>({...current,receiptName:file.name,receiptType:file.type,receiptDataUrl:String(reader.result)}));reader.readAsDataURL(file)}} className="mt-1.5 block w-full rounded-xl border p-3 text-sm font-normal file:mr-3 file:rounded-lg file:border-0 file:bg-mint file:px-3 file:py-2 file:font-semibold file:text-forest"/>{fields.receiptName&&<span className="mt-2 flex items-center gap-1 text-xs font-semibold text-forest"><FileCheck2 size={14}/>Receipt attached: {fields.receiptName}</span>}{receiptError&&<span className="mt-2 block text-xs text-coral">{receiptError}</span>}<span className="mt-1 block text-[10px] text-sage">Required · PNG, JPG, WebP or PDF · maximum 2 MB</span></label>}
 <Input label="Additional reference (optional)" value={reference} set={setReference}/></div><div className="mt-6 flex justify-end gap-2"><button onClick={close} className="h-10 rounded-xl border px-4">Cancel</button><Button disabled={!valid} onClick={submit}>Save payment</Button></div></Dialog.Content></Dialog.Portal></Dialog.Root>
}
function InvoiceDetails({invoice,close}:{invoice:Invoice;close:()=>void}){return <Dialog.Root open onOpenChange={value=>!value&&close()}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-40 bg-black/55"/><Dialog.Content className="fixed right-0 top-0 z-50 h-full w-full max-w-xl overflow-auto bg-white p-7"><Dialog.Title className="text-2xl font-bold">{invoice.number}</Dialog.Title><Dialog.Description className="mt-1 text-sm text-sage">{invoice.resident} · {invoice.residentId}</Dialog.Description><button onClick={close} className="absolute right-6 top-6"><X/></button><div className="mt-7 grid grid-cols-3 gap-3"><Amount label="Total" value={invoice.amount}/><Amount label="Paid" value={invoice.paid}/><Amount label="Balance" value={invoice.amount-invoice.paid}/></div><dl className="mt-7 grid grid-cols-2 gap-5">{[['Status',invoice.status],['Category',invoice.category],['Branch',invoice.branch],['Issue date',invoice.issueDate],['Due date',invoice.dueDate],['Description',invoice.description]].map(([label,value])=><div key={label}><dt className="eyebrow">{label}</dt><dd className="mt-1 text-sm font-semibold">{value}</dd></div>)}</dl><div className="mt-8"><p className="eyebrow">Payment history</p><div className="mt-3 divide-y rounded-xl border">{invoice.payments.length?invoice.payments.map(payment=><div key={payment.id} className="p-4"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">{payment.method}</p><p className="text-xs text-sage">{payment.date} · {payment.reference||'No reference'}</p></div><p className="font-bold">{money(payment.amount)}</p></div>{payment.details&&<div className="mt-3 flex flex-wrap gap-2">{Object.entries(payment.details).filter(([key,value])=>value&&!['receiptDataUrl','receiptType'].includes(key)).map(([key,value])=><span key={key} className="rounded-lg bg-cream px-2 py-1 text-[10px] text-sage">{key.replace(/([A-Z])/g,' $1')}: {value}</span>)}{payment.details.receiptDataUrl&&<a href={payment.details.receiptDataUrl} download={payment.details.receiptName||'payment-receipt'} className="rounded-lg bg-forest px-2 py-1 text-[10px] font-semibold text-white">Download receipt</a>}</div>}</div>):<p className="p-5 text-sm text-sage">No payments recorded.</p>}</div></div></Dialog.Content></Dialog.Portal></Dialog.Root>}
function InvoiceBadge({status}:{status:InvoiceStatus}){const style=status==='PAID'?'bg-mint text-forest':status==='OVERDUE'?'bg-[#fff0ec] text-coral':status==='PARTIALLY_PAID'?'bg-[#fff3dc] text-[#946c1f]':status==='CANCELLED'?'bg-slate-100 text-slate-500':'';return <Badge className={style}>{status.toLowerCase().replaceAll('_',' ')}</Badge>}
function PaymentMethodPreview({method,amount,invoice,fields}:{method:string;amount:number;invoice:string;fields:Record<string,string>}){
 if(method==='Bank transfer')return <div className="relative mx-auto max-w-sm overflow-hidden rounded-2xl bg-gradient-to-br from-blue-950 via-blue-800 to-cyan-600 p-5 text-white shadow-xl"><div className="absolute -right-8 -top-8 h-28 w-28 animate-pulse rounded-full bg-white/10"/><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Landmark size={22}/><span className="font-bold">Bank transfer</span></div><span className="rounded-full bg-white/15 px-2 py-1 text-[10px]">SECURE</span></div><div className="my-5 flex items-center justify-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-full bg-white/15"><Building2 size={21}/></div><div className="relative h-0.5 w-24 bg-white/30"><span className="absolute -top-1.5 h-3 w-3 animate-[pulse_1.2s_ease-in-out_infinite] rounded-full bg-cyan-200"/></div><div className="grid h-12 w-12 place-items-center rounded-full bg-white text-blue-800"><CheckCircle2 size={22}/></div></div><div className="flex justify-between text-sm"><span>{fields.transferBank||'Receiving bank'}</span><strong>{money(amount)}</strong></div><p className="mt-1 text-[10px] text-white/60">{fields.transactionId||'Transaction ID pending'}</p></div>;
 if(method==='Cheque')return <div className="relative mx-auto max-w-sm overflow-hidden rounded-2xl border bg-gradient-to-br from-white to-amber-50 p-5 text-slate-800 shadow-xl"><div className="absolute right-4 top-4 grid h-10 w-10 animate-bounce place-items-center rounded-full bg-amber-100 text-amber-700"><FileCheck2 size={19}/></div><div className="flex items-center gap-2 text-amber-800"><ReceiptText size={21}/><strong>Cheque payment</strong></div><div className="mt-6 space-y-3"><div className="h-px bg-slate-300"/><div className="flex justify-between"><span className="text-xs text-slate-500">Pay to CareNest</span><strong>{money(amount)}</strong></div><div className="h-px bg-slate-300"/><p className="text-xs">{fields.chequeBank||'Bank name'} · {fields.chequeNumber||'Cheque number'}</p></div></div>;
 if(method==='Cash')return <div className="relative mx-auto max-w-sm overflow-hidden rounded-2xl bg-gradient-to-br from-emerald-900 to-emerald-600 p-5 text-white shadow-xl"><div className="absolute right-5 top-1/2 -translate-y-1/2"><div className="grid h-20 w-32 rotate-3 animate-[pulse_1.8s_ease-in-out_infinite] place-items-center rounded-xl border-2 border-white/30 bg-emerald-400/30"><Banknote size={38}/></div><div className="absolute inset-0 -translate-x-2 -translate-y-2 rounded-xl border border-white/20"/></div><div className="relative z-10"><Banknote size={22}/><p className="mt-4 text-xs text-white/60">Cash receipt</p><p className="mt-1 text-2xl font-bold">{money(amount)}</p><p className="mt-2 text-xs">{fields.invoiceNumber||invoice}</p></div></div>;
 return <div className="relative mx-auto max-w-sm overflow-hidden rounded-2xl bg-gradient-to-br from-violet-950 via-purple-800 to-fuchsia-600 p-5 text-white shadow-xl"><div className="absolute right-5 top-5"><span className="absolute inset-0 animate-ping rounded-full bg-fuchsia-300/40"/><span className="relative grid h-12 w-12 place-items-center rounded-full bg-white/15"><Wifi size={23}/></span></div><CreditCard size={23}/><p className="mt-5 text-xs text-white/60">{fields.onlineProvider||'Online payment provider'}</p><p className="mt-1 text-2xl font-bold">{money(amount)}</p><div className="mt-4 flex items-center gap-2 text-xs"><span className={`h-2 w-2 rounded-full ${fields.receiptDataUrl?'bg-emerald-300':'animate-pulse bg-amber-300'}`}/>{fields.receiptDataUrl?'Receipt attached':'Waiting for receipt upload'}</div></div>
}
function CardPreview({holder,number,expiry,cvv,flipped}:{holder?:string;number?:string;expiry?:string;cvv?:string;flipped:boolean}){return <div className="mx-auto h-48 max-w-sm [perspective:1000px]"><div className="relative h-full w-full transition-transform duration-500 [transform-style:preserve-3d]" style={{transform:flipped?'rotateY(180deg)':'rotateY(0deg)'}}><div className="absolute inset-0 overflow-hidden rounded-2xl bg-gradient-to-br from-[#17342d] via-[#24594a] to-[#356da8] p-6 text-white shadow-xl [backface-visibility:hidden]"><div className="flex items-start justify-between"><div className="h-9 w-12 rounded-lg bg-gradient-to-br from-amber-200 to-amber-500"/><span className="text-sm font-bold tracking-widest">CareNest</span></div><p className="mt-8 font-mono text-xl tracking-[.16em]">{number||'•••• •••• •••• ••••'}</p><div className="mt-6 flex items-end justify-between"><div><p className="text-[9px] uppercase text-white/55">Card holder</p><p className="mt-1 text-sm font-semibold tracking-wide">{holder||'YOUR NAME'}</p></div><div><p className="text-[9px] uppercase text-white/55">Expires</p><p className="mt-1 font-mono text-sm">{expiry||'MM/YY'}</p></div></div></div><div className="absolute inset-0 overflow-hidden rounded-2xl bg-gradient-to-br from-[#111827] to-[#374151] py-6 text-white shadow-xl [backface-visibility:hidden] [transform:rotateY(180deg)]"><div className="h-11 bg-black/70"/><div className="mt-6 px-6"><p className="text-right text-[9px] uppercase text-white/55">Security code</p><div className="mt-1 flex h-9 items-center justify-end rounded bg-white px-3 font-mono font-bold tracking-widest text-slate-900">{cvv||'•••'}</div><p className="mt-5 text-[9px] leading-4 text-white/45">For demonstration only. Sensitive card details are not retained by CareNest.</p></div></div></div></div>}
function Input({label,value,set,type='text',onFocus,onBlur}:{label:string;value:string;set:(value:string)=>void;type?:string;onFocus?:()=>void;onBlur?:()=>void}){return <label className="text-sm font-semibold">{label}<input type={type} value={value} onChange={event=>set(event.target.value)} onFocus={onFocus} onBlur={onBlur} className="mt-1.5 h-11 w-full rounded-xl border px-3 font-normal"/></label>}
function Select({label,value,set,values}:{label:string;value:string;set:(value:any)=>void;values:string[]}){return <label className="text-sm font-semibold">{label}<select value={value} onChange={event=>set(event.target.value)} className="mt-1.5 h-11 w-full rounded-xl border bg-white px-3 font-normal">{values.map(option=><option key={option}>{option}</option>)}</select></label>}
function Summary({icon:Icon,label,value}:{icon:any;label:string;value:string}){return <div className="card flex items-center gap-4 p-5"><div className="grid h-12 w-12 place-items-center rounded-xl bg-mint text-forest"><Icon size={21}/></div><div><p className="text-sm text-sage">{label}</p><p className="text-xl font-bold">{value}</p></div></div>}
function Amount({label,value}:{label:string;value:number}){return <div className="rounded-xl bg-cream p-3 text-center"><p className="text-[10px] font-bold uppercase text-sage">{label}</p><p className="mt-1 text-sm font-bold">{money(value)}</p></div>}
