'use client';
import * as Dialog from '@radix-ui/react-dialog';
import { Building2,Edit3,Eye,MapPin,Phone,Plus,Search,Users,X } from 'lucide-react';
import { useEffect,useMemo,useState } from 'react';
import { createId } from '@/lib/id';
import { Badge,Button } from './ui';

type Branch={id:string;code:string;name:string;address:string;city:string;phone:string;email:string;manager:string;capacity:number;residents:number;staff:number;status:'ACTIVE'|'INACTIVE';notes:string};
const initial:Branch[]=[
 {id:'1',code:'BR-001',name:'Willow Grove Residence',address:'42 Lake View Road',city:'Colombo',phone:'+94 11 245 8800',email:'willow@carenest.lk',manager:'Maya Perera',capacity:64,residents:48,staff:26,status:'ACTIVE',notes:'Main residential and clinical care branch.'},
 {id:'2',code:'BR-002',name:'Sunrise Senior Living',address:'18 Temple Lane',city:'Kandy',phone:'+94 81 222 4100',email:'sunrise@carenest.lk',manager:'Nimal Silva',capacity:40,residents:31,staff:18,status:'ACTIVE',notes:'Assisted living and memory support.'},
 {id:'3',code:'BR-003',name:'Coastal Haven',address:'7 Lighthouse Avenue',city:'Galle',phone:'+94 91 223 7600',email:'coastal@carenest.lk',manager:'Pending assignment',capacity:36,residents:0,staff:4,status:'INACTIVE',notes:'Opening preparations in progress.'},
];
const blank:Omit<Branch,'id'|'residents'|'staff'>={code:'',name:'',address:'',city:'',phone:'',email:'',manager:'',capacity:0,status:'ACTIVE',notes:''};

export function BranchesPage(){
 const[mounted,setMounted]=useState(false),[branches,setBranches]=useState<Branch[]>([]),[search,setSearch]=useState(''),[filter,setFilter]=useState('ALL'),[open,setOpen]=useState(false),[editing,setEditing]=useState<Branch|null>(null),[details,setDetails]=useState<Branch|null>(null);
 useEffect(()=>{const saved=localStorage.getItem('carenest_branches');setBranches(saved?JSON.parse(saved):initial);setMounted(true)},[]);
 const persist=(next:Branch[])=>{setBranches(next);localStorage.setItem('carenest_branches',JSON.stringify(next))};
 const visible=useMemo(()=>branches.filter(branch=>`${branch.name} ${branch.code} ${branch.city} ${branch.manager}`.toLowerCase().includes(search.toLowerCase())&&(filter==='ALL'||branch.status===filter)),[branches,search,filter]);
 const changeStatus=(branch:Branch)=>persist(branches.map(item=>item.id===branch.id?{...item,status:item.status==='ACTIVE'?'INACTIVE':'ACTIVE'}:item));
 if(!mounted)return <main className="min-h-screen bg-cream lg:ml-64"><div className="p-9"><div className="h-[650px] animate-pulse rounded-2xl bg-white"/></div></main>;
 return <main className="min-h-screen lg:ml-64"><header className="border-b bg-white px-5 py-5 md:px-9"><div className="mx-auto flex max-w-[1500px] flex-wrap items-center justify-between gap-4"><div><p className="eyebrow">Organization management</p><h1 className="mt-1 text-2xl font-bold">Branches</h1><p className="mt-1 text-sm text-sage">Manage facilities, capacity, staffing and branch status.</p></div><Button onClick={()=>{setEditing(null);setOpen(true)}}><Plus size={17}/>Add branch</Button></div></header>
 <div className="mx-auto max-w-[1500px] p-5 md:p-9"><section className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Summary label="Total branches" value={branches.length} icon={Building2}/><Summary label="Active branches" value={branches.filter(b=>b.status==='ACTIVE').length} icon={Building2}/><Summary label="Total residents" value={branches.reduce((sum,b)=>sum+b.residents,0)} icon={Users}/><Summary label="Available beds" value={branches.reduce((sum,b)=>sum+Math.max(0,b.capacity-b.residents),0)} icon={Building2}/></section>
 <section className="card overflow-hidden"><div className="flex flex-col gap-3 border-b p-5 md:flex-row md:items-center md:justify-between"><div><p className="eyebrow">Facility directory</p><h2 className="mt-1 text-lg font-bold">CareNest branches</h2></div><div className="flex gap-2"><label className="relative"><Search size={17} className="absolute left-3 top-3 text-sage"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search branches..." className="h-11 w-64 rounded-xl border pl-10 pr-3 text-sm"/></label><select value={filter} onChange={e=>setFilter(e.target.value)} className="h-11 rounded-xl border bg-white px-3 text-sm font-semibold"><option value="ALL">All status</option><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></div></div>
 <div className="grid gap-5 p-5 lg:grid-cols-2 xl:grid-cols-3">{visible.map(branch=><article key={branch.id} className="rounded-2xl border p-5 transition-shadow hover:shadow-card"><div className="flex items-start justify-between"><div className="grid h-12 w-12 place-items-center rounded-xl bg-mint text-forest"><Building2 size={22}/></div><Badge className={branch.status==='INACTIVE'?'bg-slate-100 text-slate-500':''}>{branch.status}</Badge></div><p className="mt-4 text-xs font-bold text-sage">{branch.code}</p><h3 className="mt-1 text-lg font-bold">{branch.name}</h3><p className="mt-2 flex items-start gap-2 text-sm text-sage"><MapPin size={15} className="mt-0.5 shrink-0"/>{branch.address}, {branch.city}</p><p className="mt-2 flex items-center gap-2 text-sm text-sage"><Phone size={15}/>{branch.phone}</p><div className="mt-5 grid grid-cols-3 divide-x rounded-xl bg-cream p-3 text-center"><Small label="Residents" value={branch.residents}/><Small label="Capacity" value={branch.capacity}/><Small label="Staff" value={branch.staff}/></div><div className="mt-5 flex gap-2"><button onClick={()=>setDetails(branch)} className="flex h-9 flex-1 items-center justify-center gap-2 rounded-xl border text-sm font-semibold"><Eye size={15}/>Details</button><button onClick={()=>{setEditing(branch);setOpen(true)}} className="grid h-9 w-10 place-items-center rounded-xl border" aria-label="Edit branch"><Edit3 size={16}/></button><button onClick={()=>changeStatus(branch)} className={`h-9 rounded-xl px-3 text-xs font-semibold ${branch.status==='ACTIVE'?'bg-[#fff0ec] text-coral':'bg-mint text-forest'}`}>{branch.status==='ACTIVE'?'Deactivate':'Activate'}</button></div></article>)}</div>{!visible.length&&<div className="grid min-h-64 place-items-center text-center"><div><Building2 className="mx-auto text-sage"/><h3 className="mt-3 font-bold">No branches found</h3><p className="text-sm text-sage">Change your search or add a new branch.</p></div></div>}</section></div>
 <BranchDialog open={open} close={()=>setOpen(false)} branch={editing} save={branch=>{if(editing)persist(branches.map(item=>item.id===editing.id?{...item,...branch}:item));else persist([...branches,{...branch,id:createId('branch'),residents:0,staff:0}]);setOpen(false)}}/>{details&&<Details branch={details} close={()=>setDetails(null)}/>}</main>
}
function BranchDialog({open,close,branch,save}:{open:boolean;close:()=>void;branch:Branch|null;save:(branch:Omit<Branch,'id'|'residents'|'staff'>)=>void}){const[form,setForm]=useState(blank);useEffect(()=>{if(open)setForm(branch?{code:branch.code,name:branch.name,address:branch.address,city:branch.city,phone:branch.phone,email:branch.email,manager:branch.manager,capacity:branch.capacity,status:branch.status,notes:branch.notes}:blank)},[open,branch]);const field=(key:keyof typeof blank,value:string|number)=>setForm({...form,[key]:value});return <Dialog.Root open={open} onOpenChange={value=>!value&&close()}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-40 bg-black/55"/><Dialog.Content className="fixed left-1/2 top-1/2 z-50 max-h-[90vh] w-[calc(100%-2rem)] max-w-3xl -translate-x-1/2 -translate-y-1/2 overflow-auto rounded-2xl bg-white p-6"><Dialog.Title className="text-xl font-bold">{branch?'Edit branch':'Add branch'}</Dialog.Title><Dialog.Description className="mt-1 text-sm text-sage">Enter the facility and contact information.</Dialog.Description><button onClick={close} className="absolute right-5 top-5"><X/></button><div className="mt-6 grid gap-4 sm:grid-cols-2"><Input label="Branch code" value={form.code} set={v=>field('code',v)}/><Input label="Branch name" value={form.name} set={v=>field('name',v)}/><Input label="Address" value={form.address} set={v=>field('address',v)}/><Input label="City" value={form.city} set={v=>field('city',v)}/><Input label="Phone" value={form.phone} set={v=>field('phone',v)}/><Input label="Email" type="email" value={form.email} set={v=>field('email',v)}/><Input label="Branch manager" value={form.manager} set={v=>field('manager',v)}/><Input label="Resident capacity" type="number" value={String(form.capacity)} set={v=>field('capacity',Number(v))}/><label className="text-sm font-semibold">Status<select value={form.status} onChange={e=>field('status',e.target.value)} className="mt-1.5 h-11 w-full rounded-xl border bg-white px-3 font-normal"><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></label><label className="text-sm font-semibold sm:col-span-2">Notes<textarea rows={3} value={form.notes} onChange={e=>field('notes',e.target.value)} className="mt-1.5 w-full rounded-xl border p-3 font-normal"/></label></div><div className="mt-6 flex justify-end gap-2"><button onClick={close} className="h-10 rounded-xl border px-4">Cancel</button><Button disabled={!form.code||!form.name||!form.city} onClick={()=>save(form)}>Save branch</Button></div></Dialog.Content></Dialog.Portal></Dialog.Root>}
function Details({branch,close}:{branch:Branch;close:()=>void}){return <Dialog.Root open onOpenChange={value=>!value&&close()}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-40 bg-black/55"/><Dialog.Content className="fixed right-0 top-0 z-50 h-full w-full max-w-xl overflow-auto bg-white p-7"><Dialog.Title className="text-2xl font-bold">{branch.name}</Dialog.Title><Dialog.Description className="mt-1 text-sm text-sage">{branch.code} · {branch.city}</Dialog.Description><button onClick={close} className="absolute right-6 top-6"><X/></button><div className="mt-8 grid grid-cols-2 gap-5">{[['Status',branch.status],['Manager',branch.manager],['Address',`${branch.address}, ${branch.city}`],['Phone',branch.phone],['Email',branch.email],['Capacity',branch.capacity],['Residents',branch.residents],['Staff',branch.staff]].map(([label,value])=><div key={label as string}><p className="eyebrow">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>)}</div><div className="mt-7 rounded-xl bg-mint p-4"><p className="eyebrow">Branch notes</p><p className="mt-2 text-sm">{branch.notes||'No notes recorded.'}</p></div></Dialog.Content></Dialog.Portal></Dialog.Root>}
function Input({label,value,set,type='text'}:{label:string;value:string;set:(value:string)=>void;type?:string}){return <label className="text-sm font-semibold">{label}<input type={type} value={value} onChange={e=>set(e.target.value)} className="mt-1.5 h-11 w-full rounded-xl border px-3 font-normal"/></label>}
function Summary({label,value,icon:Icon}:{label:string;value:number;icon:any}){return <div className="card flex items-center gap-4 p-5"><div className="grid h-12 w-12 place-items-center rounded-xl bg-mint text-forest"><Icon size={21}/></div><div><p className="text-sm text-sage">{label}</p><p className="text-2xl font-bold">{value}</p></div></div>}
function Small({label,value}:{label:string;value:number}){return <div><p className="font-bold">{value}</p><p className="text-[11px] text-sage">{label}</p></div>}
