'use client';
import { useQuery } from '@tanstack/react-query';
import { Activity,AlertTriangle,CheckCircle2,Download,FileSpreadsheet,FileText,Printer,RefreshCw,Users } from 'lucide-react';
import { useEffect,useMemo,useState } from 'react';
import { api } from '@/lib/api';
import { Badge,Button,Skeleton } from './ui';

type ReportType='Overview'|'Residents'|'Care tasks'|'Medication'|'Staff'|'Daily health';
const types:ReportType[]=['Overview','Residents','Care tasks','Medication','Staff','Daily health'];
const iso=(date:Date)=>date.toISOString().slice(0,10);
const escape=(value:unknown)=>`"${String(value??'').replaceAll('"','""')}"`;

export function ReportsPage(){
 const[type,setType]=useState<ReportType>('Overview'),[from,setFrom]=useState(''),[to,setTo]=useState('');
 useEffect(()=>{const end=new Date(),start=new Date();start.setDate(end.getDate()-30);setFrom(iso(start));setTo(iso(end))},[]);
 const residents=useQuery({queryKey:['residents'],queryFn:api.residents}),tasks=useQuery({queryKey:['tasks'],queryFn:api.tasks}),medications=useQuery({queryKey:['medications'],queryFn:api.medications}),staff=useQuery({queryKey:['staff'],queryFn:api.staff}),health=useQuery({queryKey:['daily-health-reports'],queryFn:()=>api.dailyHealth()});
 const loading=[residents,tasks,medications,staff,health].some(q=>q.isLoading);
 const filteredTasks=(tasks.data??[]).filter(t=>(!from||t.dueAt.slice(0,10)>=from)&&(!to||t.dueAt.slice(0,10)<=to));
 const filteredHealth=(health.data??[]).filter(r=>(!from||r.reportDate.slice(0,10)>=from)&&(!to||r.reportDate.slice(0,10)<=to));
 const completed=filteredTasks.filter(t=>t.status==='COMPLETED').length,completion=filteredTasks.length?Math.round(completed/filteredTasks.length*100):0;
 const lowStock=(medications.data??[]).filter(m=>m.stockQuantity<=m.reorderLevel).length;
 const rows=useMemo(():string[][]=>{
  if(type==='Residents')return (residents.data??[]).map(r=>[r.firstName+' '+r.lastName,r.room,r.status,r.priority,String(r.medications.length),r.allergies.join(', ')||'None']);
  if(type==='Care tasks')return filteredTasks.map(t=>[t.title,t.resident.firstName+' '+t.resident.lastName,t.category,new Date(t.dueAt).toLocaleString(),t.status,t.assignee?`${t.assignee.firstName} ${t.assignee.lastName}`:'Unassigned']);
  if(type==='Medication')return (medications.data??[]).map(m=>[m.name,m.resident.firstName+' '+m.resident.lastName,m.dosage,m.frequency,`${m.stockQuantity} ${m.stockUnit}`,m.active?'Active':'Inactive']);
  if(type==='Staff')return (staff.data??[]).map(s=>[s.firstName+' '+s.lastName,s.employeeId||'—',s.role,s.department||'—',s.status,s.email]);
  if(type==='Daily health')return filteredHealth.map(r=>[r.reportDate,r.resident.firstName+' '+r.resident.lastName,r.bloodPressure||'—',r.pulse?.toString()||'—',r.temperature?.toString()||'—',r.healthChange?'Health change':'Stable']);
  return [['Active residents',String((residents.data??[]).filter(r=>r.status==='ACTIVE').length)],['Task completion',`${completion}%`],['Health checks',String(filteredHealth.length)],['Low-stock medicines',String(lowStock)],['Active staff',String((staff.data??[]).filter(s=>s.status==='ACTIVE').length)]];
 },[type,residents.data,filteredTasks,medications.data,staff.data,filteredHealth,completion,lowStock]);
 const headers=type==='Residents'?['Resident','Room','Status','Priority','Medicines','Allergies']:type==='Care tasks'?['Task','Resident','Category','Due','Status','Assigned staff']:type==='Medication'?['Medicine','Resident','Dosage','Frequency','Stock','Status']:type==='Staff'?['Staff member','Employee ID','Role','Department','Status','Email']:type==='Daily health'?['Date','Resident','Blood pressure','Pulse','Temperature','Condition']:['Metric','Value'];
 const filename=`carenest-${type.toLowerCase().replaceAll(' ','-')}-${from}-${to}`;
 const saveBlob=(blob:Blob,extension:string)=>{const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`${filename}.${extension}`;link.click();URL.revokeObjectURL(link.href)};
 const downloadCsv=()=>{const csv=[headers,...rows].map(row=>row.map(escape).join(',')).join('\r\n');saveBlob(new Blob(['\uFEFF',csv],{type:'text/csv;charset=utf-8'}),'csv')};
 const downloadExcel=()=>{const cells=(row:string[],tag:string)=>`<tr>${row.map(value=>`<${tag} style="border:1px solid #dfe8e3;padding:8px;text-align:left">${html(value)}</${tag}>`).join('')}</tr>`;const sheet=`<html><head><meta charset="UTF-8"></head><body><h2>CareNest ${html(type)} Report</h2><p>Reporting period: ${html(from)} to ${html(to)}</p><table style="border-collapse:collapse;font-family:Arial">${cells(headers,'th')}${rows.map(row=>cells(row,'td')).join('')}</table></body></html>`;saveBlob(new Blob(['\uFEFF',sheet],{type:'application/vnd.ms-excel;charset=utf-8'}),'xls')};
 const downloadPdf=()=>saveBlob(makePdf(`CareNest ${type} Report`,[`Reporting period: ${from||'All'} to ${to||'Today'}`,'',headers.join(' | '),...rows.map(row=>row.join(' | '))]),'pdf');
 const refresh=()=>Promise.all([residents.refetch(),tasks.refetch(),medications.refetch(),staff.refetch(),health.refetch()]);
 return <main className="min-h-screen lg:ml-64"><header className="border-b bg-white px-5 py-5 md:px-9"><div className="mx-auto flex max-w-[1500px] flex-wrap items-center justify-between gap-4"><div><p className="eyebrow">Insights & compliance</p><h1 className="mt-1 text-2xl font-bold">Reports</h1><p className="mt-1 text-sm text-sage">Review resident care, clinical activity and operational performance.</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>window.print()} className="focus-ring flex h-10 items-center gap-2 rounded-xl border bg-white px-3 text-sm font-semibold"><Printer size={16}/>Print</button><button onClick={downloadCsv} className="focus-ring flex h-10 items-center gap-2 rounded-xl border bg-white px-3 text-sm font-semibold"><Download size={16}/>CSV</button><button onClick={downloadExcel} className="focus-ring flex h-10 items-center gap-2 rounded-xl border bg-white px-3 text-sm font-semibold"><FileSpreadsheet size={16}/>Excel</button><Button onClick={downloadPdf}><FileText size={16}/>PDF</Button></div></div></header>
 <div className="mx-auto max-w-[1500px] p-5 md:p-9"><section className="card mb-6 flex flex-wrap items-end gap-4 p-5"><label className="text-sm font-semibold">Report type<select value={type} onChange={e=>setType(e.target.value as ReportType)} className="mt-1.5 block h-11 min-w-48 rounded-xl border bg-white px-3 font-normal">{types.map(t=><option key={t}>{t}</option>)}</select></label><label className="text-sm font-semibold">From<input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="mt-1.5 block h-11 rounded-xl border px-3 font-normal"/></label><label className="text-sm font-semibold">To<input type="date" value={to} min={from} onChange={e=>setTo(e.target.value)} className="mt-1.5 block h-11 rounded-xl border px-3 font-normal"/></label><button onClick={refresh} className="focus-ring flex h-11 items-center gap-2 rounded-xl border px-4 text-sm font-semibold"><RefreshCw size={16}/>Refresh data</button><p className="ml-auto pb-3 text-xs text-sage">Reporting period: {from||'All'} to {to||'Today'}</p></section>
 {loading?<Skeleton className="h-[600px]"/>:<><section className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric icon={Users} label="Active residents" value={(residents.data??[]).filter(r=>r.status==='ACTIVE').length} tone="bg-mint text-forest"/><Metric icon={CheckCircle2} label="Task completion" value={`${completion}%`} tone="bg-blue-50 text-blue-700"/><Metric icon={Activity} label="Health checks" value={filteredHealth.length} tone="bg-purple-50 text-purple-700"/><Metric icon={AlertTriangle} label="Low stock" value={lowStock} tone="bg-orange-50 text-orange-700"/><Metric icon={Users} label="Active staff" value={(staff.data??[]).filter(s=>s.status==='ACTIVE').length} tone="bg-slate-100 text-slate-700"/></section>
 <section className="mb-6 grid gap-6 xl:grid-cols-[1.3fr_.7fr]"><div className="card p-5"><p className="eyebrow">Task performance</p><h2 className="mt-1 text-lg font-bold">Care task status</h2><div className="mt-7 space-y-5">{['COMPLETED','IN_PROGRESS','PENDING','MISSED'].map(status=><Bar key={status} label={status.replace('_',' ')} value={filteredTasks.filter(t=>t.status===status).length} total={Math.max(filteredTasks.length,1)}/>)}</div></div><div className="card p-5"><p className="eyebrow">Resident acuity</p><h2 className="mt-1 text-lg font-bold">Care priority</h2><div className="mt-6 grid grid-cols-2 gap-3">{['LOW','MEDIUM','HIGH','CRITICAL'].map(priority=><div key={priority} className="rounded-xl bg-cream p-4"><p className="text-xs font-bold text-sage">{priority}</p><p className="mt-1 text-2xl font-bold">{(residents.data??[]).filter(r=>r.priority===priority).length}</p></div>)}</div></div></section>
 <section className="card overflow-hidden"><div className="flex items-center justify-between border-b p-5"><div><p className="eyebrow">Report detail</p><h2 className="mt-1 text-lg font-bold">{type} report</h2></div><Badge>{rows.length} records</Badge></div><div className="overflow-x-auto"><table className="w-full text-left"><thead><tr className="bg-cream/60 text-[11px] uppercase tracking-wider text-sage">{headers.map(h=><th key={h} className="px-5 py-3">{h}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index} className="border-t hover:bg-mint/20">{row.map((cell,i)=><td key={i} className="px-5 py-4 text-sm">{cell}</td>)}</tr>)}</tbody></table></div></section></>}</div></main>
}
function Metric({icon:Icon,label,value,tone}:{icon:any;label:string;value:string|number;tone:string}){return <div className="card flex items-center gap-4 p-5"><div className={`grid h-11 w-11 place-items-center rounded-xl ${tone}`}><Icon size={20}/></div><div><p className="text-xs text-sage">{label}</p><p className="text-2xl font-bold">{value}</p></div></div>}
function Bar({label,value,total}:{label:string;value:number;total:number}){const percentage=Math.round(value/total*100);return <div><div className="mb-2 flex justify-between text-sm"><span className="font-semibold">{label}</span><span className="text-sage">{value} · {percentage}%</span></div><div className="h-2.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-forest" style={{width:`${percentage}%`}}/></div></div>}
function html(value:unknown){return String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function makePdf(title:string,sourceLines:string[]){
 const clean=(value:string)=>value.normalize('NFKD').replace(/[^\x20-\x7E]/g,' ').replaceAll('\\','\\\\').replaceAll('(','\\(').replaceAll(')','\\)');
 const lines=sourceLines.flatMap(line=>{const text=clean(line);const chunks:string[]=[];for(let i=0;i<text.length;i+=105)chunks.push(text.slice(i,i+105));return chunks.length?chunks:['']});
 const pages=Array.from({length:Math.max(1,Math.ceil(lines.length/48))},(_,index)=>lines.slice(index*48,(index+1)*48));
 const fontId=3+pages.length*2,objects:string[]=[];objects[1]='<< /Type /Catalog /Pages 2 0 R >>';
 objects[2]=`<< /Type /Pages /Kids [${pages.map((_,i)=>`${3+i*2} 0 R`).join(' ')}] /Count ${pages.length} >>`;
 pages.forEach((page,index)=>{const pageId=3+index*2,contentId=pageId+1;const content=`BT /F1 14 Tf 40 805 Td (${clean(title)}) Tj 0 -22 Td /F1 8 Tf 11 TL ${page.map((line,i)=>`${i?'T* ':''}(${line}) Tj`).join(' ')} ET`;objects[pageId]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${fontId} 0 R >> >> /Contents ${contentId} 0 R >>`;objects[contentId]=`<< /Length ${content.length} >>\nstream\n${content}\nendstream`});
 objects[fontId]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';
 let pdf='%PDF-1.4\n',offsets=[0];for(let id=1;id<objects.length;id++){offsets[id]=pdf.length;pdf+=`${id} 0 obj\n${objects[id]}\nendobj\n`}const xref=pdf.length;pdf+=`xref\n0 ${objects.length}\n0000000000 65535 f \n`;for(let id=1;id<objects.length;id++)pdf+=`${String(offsets[id]).padStart(10,'0')} 00000 n \n`;pdf+=`trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return new Blob([pdf],{type:'application/pdf'});
}
